# Generated by Django 6.0.1 on 2026-01-16 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_link', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Короткая ссылка')),
                ('original_link', models.URLField(max_length=2048, verbose_name='Оригинальная ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
                'ordering': ('-created_at',),
            },
        ),
    ]
